version: '3.5'

services:
  edge-service:
    image: dev.local/edge-service:0.1
    container_name: edge-service
    ports:
      - 8080:8080
    command: ["host.docker.internal", "1883", "mytopic-response"]